### ISSUE TITLE
Includes unknown references

### ISSUE THREAD

**Issue by Relequestual** [ga4gh-schemablocks/blocks-json-schema#3]
You should only reference other schemas that actually exists, not ones that do not yet exist.
For example
https://github.com/ga4gh-schemablocks/blocks-json-schema/blob/e3d0e382cf245c544427c32b8633ab8cda70f624/src/yaml/Individual.yaml#L42-L46

Of course, I understand if you intend to add these soon, but still feel I should highlight the issue.

**Comment by theisuru** [comment]
Fixed all non-referenced messages
